polling/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name= 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime
from django.utils import timezone
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    name_text = models.CharField(max_length=100, default='')
    email_text=models.EmailField(max_length=100, default='')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404

from .models import Question

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    return HttpResponse("You're looking at the results of question %s." % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

polls/templates/index.html
<html>
    <head>
        <title>Poll Title</title>
        <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
        <link rel = "stylesheet" type = "text/css" href = "styles.css" />      
    </head>
    
    <body>
        <div class = "heading">
            <h1 >Poll Title</h1>      
        </div>
    
        <div class = "container">
            <form>
                <input type="text" placeholder="Name">
                <input type="text" placeholder="E-mail Address">
                <input type="checkbox">
                <input type="button" value="submit">
            </form>
        </div>
        

    </body>
</html>

polls/templates/polls/details.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/index_1.html
<!--DJANGO BASED POLLING APP-->
<html>
    <head>
        <title>Poll Title</title>
        <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
        <link rel = "stylesheet" type = "text/css" href = "styles.css" />      
    </head>
    
    <body>
        <div class = "heading">
            <h1 >Poll Title</h1>      
        </div>
    
        <div class = "container">
            <form>
                <input type="text" placeholder="Name">
                <input type="text" placeholder="E-mail Address">
                <input type="checkbox">
                <input type="button" value="submit">
            </form>
        </div>
        

    </body>
</html>

polls/templates/polls/index_2.html
<html>
    <head>
        <title>Poll Title</title>
        <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
        <link rel = "stylesheet" type = "text/css" href = "styles.css" />      
    </head>
    
    <body>
        <div class = "heading">
            <h1 >Poll Title</h1>      
        </div>
    
        <div class = "container">
            <form>
                <input type="text" placeholder="Name">
                <input type="text" placeholder="E-mail Address">
                <input type="checkbox">
                <input type="button" value="submit">
            </form>
        </div>
        

    </body>
</html>